[env:esp32dev]
platform = espressif32@^6.13.0
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps = 
    cJSON@^1.7.18
    # Added per phase


